---
ios1:
    hostname: cisco1.twb-tech.com
    groups: 
      - ios

ios2:
    hostname: cisco2.twb-tech.com
    groups: 
      - ios

nxos1:
    hostname: nxos1.twb-tech.com
    groups: 
      - nxos

nxos2:
    hostname: nxos2.twb-tech.com
    groups: 
      - nxos_ssh

arista1:
    hostname: arista1.twb-tech.com
    groups: 
      - eos

arista2:
    hostname: arista2.twb-tech.com
    groups: 
      - eos

srx1:
    hostname: srx1.twb-tech.com
    groups: 
      - junos
